name: stackfood_multivendor_restaurant
description: An application for multivendor ecommerce restaurant.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.6.6
  shared_preferences: ^2.2.3
  connectivity_plus: ^5.0.2
  firebase_core: ^2.4.1
  firebase_messaging: ^14.2.1
  flutter_local_notifications: ^16.3.0
  path_provider: ^2.0.8
  url_strategy: ^0.2.0
  shimmer_animation: ^2.0.0
  image_picker: ^1.0.7
  http: ^1.1.2
  pin_code_fields: ^8.0.1
  url_launcher: ^6.1.2
  vibration: ^1.7.6
  audioplayers: ^5.2.1
  flutter_switch: ^0.3.2
  flutter_typeahead: ^4.0.0
  phone_numbers_parser: ^8.1.3
  country_code_picker: ^3.0.0
  flutter_widget_from_html_core: ^0.14.11
  google_maps_flutter: ^2.1.1
  geolocator: ^10.1.0
  card_swiper: ^3.0.1
#  flutter_pos_printer_platform: ^1.1.0
#  esc_pos_utils: ^1.1.0
  print_bluetooth_thermal: ^1.1.0
#  esc_pos_utils_plus: ^2.0.3
  flutter_esc_pos_utils: ^1.0.1
  screenshot: ^3.0.0
  image: ^4.2.0
  modal_bottom_sheet: ^2.1.2
  intl: ^0.19.0
  path: ^1.8.2
  http_parser: ^4.0.2
  dotted_border: ^2.1.0
  carousel_slider: ^4.0.0
  photo_view: ^0.14.0
  flutter_inappwebview: ^6.0.0
  just_the_tooltip: ^0.0.12
  file_picker: ^6.0.0
  custom_info_window: ^1.0.1
  syncfusion_flutter_charts: ^25.2.5
  permission_handler: ^11.3.1
  flutter_svg: ^2.0.10+1
  another_flushbar: ^1.12.30
  flutter_slidable: ^3.1.0
  video_player: ^2.8.6
  chewie: ^1.8.1
  fluttertoast: ^8.2.5
  pdf: ^3.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/image/
    - assets/language/
    - assets/notification.mp3

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/font/Roboto-Regular.ttf
          weight: 400
        - asset: assets/font/Roboto-Medium.ttf
          weight: 500
        - asset: assets/font/Roboto-Bold.ttf
          weight: 700
        - asset: assets/font/Roboto-Black.ttf
          weight: 900